# DHS Cross Country Refactor Tests

This notebook tests the refactors made to `dhs.py` to accomodate cross-country operations.

In [165]:
import sys
sys.path.append("../../")

from relativewealth import settings
from relativewealth.dhs import DHSDataManager
from geowrangler import dhs

In [166]:
%reload_ext autoreload
%autoreload 2

In [167]:
dhsmanager = DHSDataManager()

In [168]:
dhsmanager.view_cache_keys()

Household:  [] Cluster:  []

In [169]:
# Set country-specific variables
country_config = {
    'Philippines': {
        'country_osm':'philippines',
        'ookla_year': 2019,
        'nightlights_year' : 2017,
        'country_code': 'ph',
        'dhs_household_dta_path' : settings.DATA_DIR/"dhs/ph/PHHR71DT/PHHR71FL.DTA",
        'dhs_geographic_shp_path' : settings.DATA_DIR/"dhs/ph/PHGE71FL/PHGE71FL.shp"
    },
    'Timor Leste': {
        'country_osm':'east-timor',
        'ookla_year': 2019,
        'nightlights_year' : 2016,
        'country_code': 'tl',
        'dhs_household_dta_path' : settings.DATA_DIR/"dhs/tl/TLHR71DT/TLHR71FL.DTA",
        'dhs_geographic_shp_path' : settings.DATA_DIR/"dhs/tl/TLGE71FL/TLGE71FL.shp"
    },
    'Cambodia': {
        'country_osm':'cambodia',
        'ookla_year': 2019,
        'nightlights_year' : 2014,
        'country_code': 'kh',
        'dhs_household_dta_path' : settings.DATA_DIR/"dhs/kh/KHHR73DT/KHHR73FL.DTA",
        'dhs_geographic_shp_path' : settings.DATA_DIR/"dhs/kh/KHGE71FL/KHGE71FL.shp"
    },
    'Myanmar': {
        'country_osm':'myanmar',
        'ookla_year': 2019,
        'nightlights_year' : 2015,
        'country_code': 'mm',
        'dhs_household_dta_path' : settings.DATA_DIR/"dhs/mm/MMHR71DT/MMHR71FL.DTA",
        'dhs_geographic_shp_path' : settings.DATA_DIR/"dhs/mm/MMGE71FL/MMGE71FL.shp"
    }
}

In [170]:
dhsmanager.generate_dhs_household_level_data(
    'Timor Leste',
    country_config['Timor Leste']['dhs_household_dta_path'],
    col_rename_config=country_config['Timor Leste']['country_code'], 
    overwrite_cache=True
)

Overwriting Timor Leste in cache

      case identification  ... country_index
0                    1  1  ...   Timor Leste
1                    1  2  ...   Timor Leste
2                    1  3  ...   Timor Leste
3                    1  4  ...   Timor Leste
4                    1  5  ...   Timor Leste
...                   ...  ...           ...
11497              455 22  ...   Timor Leste
11498              455 23  ...   Timor Leste
11499              455 24  ...   Timor Leste
11500              455 25  ...   Timor Leste
11501              455 26  ...   Timor Leste

[11502 rows x 317 columns]

In [171]:
dhsmanager.generate_dhs_household_level_data(
    'Philippines',
    country_config['Philippines']['dhs_household_dta_path'],
    col_rename_config=country_config['Philippines']['country_code'], 
    overwrite_cache=True
)

Overwriting Philippines in cache

      case identification  ... country_index
0                00010001  ...   Philippines
1                00010002  ...   Philippines
2                00010004  ...   Philippines
3                00010007  ...   Philippines
4                00010008  ...   Philippines
...                   ...  ...           ...
27491            12500022  ...   Philippines
27492            12500023  ...   Philippines
27493            12500024  ...   Philippines
27494            12500025  ...   Philippines
27495            12500026  ...   Philippines

[27496 rows x 549 columns]

In [172]:
dhsmanager.view_cache_keys()

Household:  ['Timor Leste', 'Philippines'] Cluster:  []

In [173]:
dhsmanager.generate_dhs_cluster_level_data(
    'Philippines',
    country_config['Philippines']['dhs_household_dta_path'],
    country_config['Philippines']['dhs_geographic_shp_path'],
    col_rename_config=country_config['Philippines']['country_code'], 
    overwrite_cache=True
)

Overwriting Philippines in cache
Overwriting Philippines in cache

      DHSCLUST  ...  country_index
0            1  ...    Philippines
1            2  ...    Philippines
2            3  ...    Philippines
3            4  ...    Philippines
5            6  ...    Philippines
...        ...  ...            ...
1244      1246  ...    Philippines
1245      1247  ...    Philippines
1246      1248  ...    Philippines
1247      1249  ...    Philippines
1248      1250  ...    Philippines

[1213 rows x 23 columns]

In [174]:
dhsmanager.generate_dhs_cluster_level_data(
    'Timor Leste',
    country_config['Timor Leste']['dhs_household_dta_path'],
    country_config['Timor Leste']['dhs_geographic_shp_path'],
    col_rename_config=country_config['Timor Leste']['country_code'], 
    overwrite_cache=True
)

Overwriting Timor Leste in cache
Overwriting Timor Leste in cache

     DHSCLUST  ...  country_index
0           1  ...    Timor Leste
1           2  ...    Timor Leste
2           3  ...    Timor Leste
3           4  ...    Timor Leste
4           5  ...    Timor Leste
..        ...  ...            ...
450       451  ...    Timor Leste
451       452  ...    Timor Leste
452       453  ...    Timor Leste
453       454  ...    Timor Leste
454       455  ...    Timor Leste

[455 rows x 26 columns]

In [182]:
dhsmanager.view_cache_keys()

Household:  ['Timor Leste', 'Philippines'] Cluster:  ['Philippines', 'Timor Leste']

In [183]:
dhsmanager.get_household_level_data_by_country(drop_extra_cols=False)

Combining household data for the ff. countries: ['Timor Leste', 'Philippines']

      case identification  ... why he/she did not get philhealth benefits - don't know
0                    1  1  ...                                                NaN
1                    1  2  ...                                                NaN
2                    1  3  ...                                                NaN
3                    1  4  ...                                                NaN
4                    1  5  ...                                                NaN
...                   ...  ...                                                ...
38993            12500022  ...                                                NaN
38994            12500023  ...                                                0.0
38995            12500024  ...                                                NaN
38996            12500025  ...                                                NaN
38997            12500026  ...                                                NaN

[38998 rows x 717 columns]

In [184]:
dhsmanager.get_cluster_level_data_by_country(drop_extra_cols=True)

Combining cluster data for the ff. countries: ['Timor Leste', 'Philippines']

      DHSCLUST  ...  country_index
0            1  ...    Timor Leste
1            2  ...    Timor Leste
2            3  ...    Timor Leste
3            4  ...    Timor Leste
4            5  ...    Timor Leste
...        ...  ...            ...
1663      1246  ...    Philippines
1664      1247  ...    Philippines
1665      1248  ...    Philippines
1666      1249  ...    Philippines
1667      1250  ...    Philippines

[1668 rows x 23 columns]

In [178]:
dhsmanager.recompute_index_household_level()[['DHSCLUST', 'Wealth Index', 'Recomputed Wealth Index']]

Combining household data for the ff. countries: ['Timor Leste', 'Philippines']

       DHSCLUST  Wealth Index  Recomputed Wealth Index
0             1         25643                11.262147
1             1         26545                21.185194
2             1        135626                33.320456
3             1         64157                33.107983
4             1        101871                13.504908
...         ...           ...                      ...
38993      1250       -112963                14.345640
38994      1250        -59817                43.077177
38995      1250        -90503                41.449333
38996      1250        -38813                12.261886
38997      1250        -65616                43.049074

[38998 rows x 3 columns]

In [203]:
dhsmanager.recompute_index_cluster_level()[["country_index", "DHSCLUST", "Wealth Index", "Recomputed Wealth Index"]].sort_values(["DHSCLUST", "country_index"]).head(20)

Combining household data for the ff. countries: ['Philippines', 'Timor Leste']
Combining cluster data for the ff. countries: ['Philippines', 'Timor Leste']

     country_index  DHSCLUST   Wealth Index  Recomputed Wealth Index
0      Philippines         1  -31881.608696                18.344515
1213   Timor Leste         1   32166.600000                27.838472
1      Philippines         2   -2855.375000                16.777943
1214   Timor Leste         2  -34063.923077                25.325837
2      Philippines         3  -57647.047619                31.901361
1215   Timor Leste         3   39230.590909                21.298537
3      Philippines         4  -54952.666667                22.347460
1216   Timor Leste         4  -82140.227273                35.746996
1217   Timor Leste         5  -56203.423077                24.733723
4      Philippines         6  -80701.695652                34.146176
1218   Timor Leste         6  -24628.782609                38.904106
5      Philippines         7  -62490.538462                33.656503
1219   Timor Leste         7  -33729.125000                35.140802
6      Philippines         8  -80889.666667                22.978165
1220   Timor Leste         8   15977.076923                18.614688
7      Philippines         9  -77994.520000                35.357400
1221   Timor Leste         9    5330.440000                13.824022
8      Philippines        10 -135511.961538                33.195019
1222   Timor Leste        10  100213.520000                16.869888
9      Philippines        11 -107304.250000                14.627833

In [ ]:
dhs.load_column_config('kh')

{'cluster number': 'DHSCLUST',
 'wealth index factor score (5 decimals)': 'Wealth Index',
 'country code and phase': 'country code and phase',
 'number of rooms used for sleeping': 'rooms',
 'has electricity': 'electric',
 'has mobile telephone': 'mobile telephone',
 'has radio': 'radio',
 'has television': 'television',
 'has car/truck': 'car/truck',
 'has refrigerator': 'refrigerator',
 'has motorcycle/scooter': 'motorcycle',
 'main floor material': 'floor',
 'type of toilet facility': 'toilet',
 'na - source of drinking water': 'drinking water'}